service: serverless-crud

provider:
  name: aws
  runtime: nodejs8.10
  versionFunctions: false
  environment:
    BOOK_TABLE_NAME: ${self:service}-${self:provider.stage}-books
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::Join:
          - ':'
          -
            - 'arn:aws:dynamodb:${self:provider.region}'
            - Ref: 'AWS::AccountId'
            - 'table/${self:service}-${self:provider.stage}-books*'

functions:
  hello:
    handler: src/hello-handler.handler
    events:
      - http:
          path: hello
          method: get
  createBook:
    handler: src/book/createBook-handler.handler
    events:
      - http:
          path: book
          method: post
  getBook:
    handler: src/book/getBook-handler.handler
    events:
      - http:
          path: book
          method: get
  updateBook:
    handler: src/book/updateBook-handler.handler
    events:
      - http:
          path: book
          method: put
  deleteBook:
    handler: src/book/deleteBook-handler.handler
    events:
      - http:
          path: book
          method: delete

resources:
  Resources:
    BooksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-books
        AttributeDefinitions:
          - AttributeName: bookId
            AttributeType: S
        KeySchema:
          - AttributeName: bookId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1