service: serverless-crud

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: src/hello-handler.handler
    events:
        - http:
            path: hello
            method: get
